sudo: required

dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - docker

script:
  - sudo find / -name my.cnf
  - sudo find / -name mysqld.sock
  - sudo cat /etc/mysql/my.cnf
  - sudo ps -ef | grep mysql
  - sudo find / -name mysql*
