sudo: required

dist: trusty

services:
  - mysql
  - docker

script:
  - sudo find / -name my.cnf
  - sudo find / -name mysqld.sock
  - sudo cat /etc/mysql/my.cnf
  - sudo ps -ef | grep mysql
  - sudo find / mysql*
