language: go

go: 
  - 1.5.3

env: 
  - GO15VENDOREXPERIMENT=1

before_install: 
  - go get github.com/go-sql-driver/mysql
  - mysql < ./registry.sql --verbose -uroot

install: true

script: go test ./...
